version: "2"
services:
  nginx:
      build:
          context: ./nginx
      ports:
          - "8080:80"
      expose:
          - "80"
      volumes:
          - ./app:/var/app
      environment:
          - VIRTUAL_HOST=box.dev,backend.box.dev
      restart: unless-stopped
  fpm:
      build:
          context: ./fpm
      volumes:
          - ./app:/var/app
      expose:
          - "9000"
  db:
      image: mariadb
      ports:
          - "3306:3306"
      environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=db_box
      volumes:
          - ./storage/mariadb:/var/lib/mysql
  mongodb:
      build:
        context: ./mongodb
      ports:
        - "27017:27017"
        - "28017:28017"
      environment:
        - AUTH=no
        - MONGODB_DATABASE=db_box
      volumes:
        - ./storage/mongodb:/data/db
  redis:
      build:
        context: ./redis
      ports:
        - "6379:6379"
      volumes:
        - ./storage/redis:/data
      command: redis-server --appendonly yes
  elasticsearch:
      build:
        context: ./elasticsearch
      ports:
        - "9200:9200"
      volumes:
        - ./storage/elasticsearch:/usr/share/elasticsearch/data
  kibana:
      build:
        context: ./kibana
      ports:
        - "5601:5601"